### ISSUE TITLE
Core hangs after short time

### ISSUE THREAD

**Issue by TomnPhobos** [sorgelig/BK0011M_MIST#1]
Hi,

first of all Thanks for this interesting core :-)
I tried it out, but i have some problems with it. It starts normal, but after a short time it hangs with a distorted screen. You can see the output here:

![dsc_0382](https://cloud.githubusercontent.com/assets/17750695/13664807/94fbe206-e6a9-11e5-9598-aebae6ee7885.jpg)

I checked it with different SD cards, also complete new and empty cards, but without success. 
It would be great if you find the source of the problem. Please let me know if you need some more informations or if i can help in any way.

Best wishes
Thomas

**Comment by sorgelig** [comment]
How much time approximately passed before this issue? Did you load any applications or not?
As i guess you are from german board. Is anyone else having the same issue or only you?

**Comment by TomnPhobos** [comment]
It's only a few seconds/minutes before the issue occures. After a reboot of the system it seems that the error occurs nearly directly. I start the core, then strange things happen like CRs, strange output, distorted screens etc. Next weekend i can make a video of it so you can see what happens. 
Yes, i'm from a german board, [http://www.mist-fpga.net](url). I think here i'm the only user who tested the core ;) Till Harbaum (the developer of the board) told me that maybe the programming of the core sometimes use the limits of the FPGA so some machines are off that limit. 
Do you know if there are other users that have these problems?

**Comment by sorgelig** [comment]
It's a problem to get user base. This is russian computer, and therefore it mostly used in Russia and some other ex-USSR countries. But here is the problem: MiST board is one of most expensive board of such kind, so i don't know any russian user with this board. All russian potential users refused to buy MiST because of high price. I like this board, but frankly speaking it's overpriced. So, actually I'm the only who tested this core. I was surprised that some foreigners use it ;)
May be SDRAM clock is high, and thus not all boards work ok on this frequency.

Did you try my [ZX Spectrum core](https://github.com/sorgelig/ZX_Spectrum-128K_MIST)? It uses the same SDRAM module. It would be interesting to know if you have similar problem with that core as well or not.

**Comment by sorgelig** [comment]
Try this version: http://www.mediafire.com/download/87jd2flmid12odo/bk0011m_20160310.rbf

**Comment by TomnPhobos** [comment]
Hehe, well, i like exotic computers and when i heard about the BK0011-implementation first i had to google about it ;) I like the fact that a PDP11 architecture was used as a home computer. I also searched eBay because nowi also want to buy the "real thing" :-)
I tried the ZX Spectrum core of the MiST repository. It's the version from 30.12.2015. I actually did not much with it, started it only and played around with ESXDOS. But here i didn't had problems. I see that you have newer versions in your repository, i'll check out the latest version :-)
Thanks for the new version of the BK0011 core. Actually i'll  have my MiST back this weekend (actually it's at my girlfriends home ;)), so i'll try it out then. Have you changed the SDRAM clock? It could really be the problem. I have a really old board (one of the first boards ;-)) so it could be that newer boards can handle higher clocks than older boards.
I'll check out the new core this week end and let you know about the results :-)

**Comment by sorgelig** [comment]
Here is another version with reduced SDRAM clock. Originally was 120mhz. I've reduced it to 96MHz.
http://www.mediafire.com/download/bwd8wprb9aszd3n/bk0011m_20160310_2.rbf

ZX Spectrum in MiST repository is completely different core. So, you need to try my ZX core from link i gave above.

**Comment by sorgelig** [comment]
one more version for test:
http://www.mediafire.com/download/dranov2kx3jxo5w/bk0011m_20160310_3.rbf
I've lowered SDRAM freq to 72MHz. This should be close to minimum possible frequency for current concept of SRAM emulation.

**Comment by sorgelig** [comment]
Real BK0011M (don't mess with BK0011 without M!) will be hard to maintain. You won't like to use archaic 5.25" disks and drive which is hard to find today. HDD addon was kind of DIY addon.
My core has full read and write support for HDD images, so you won't loose anything.
I'm planning to improve the core to make it 100% match to real by timings.

**Comment by TomnPhobos** [comment]
Sounds great, i'm, looking forward to it :-)

**Comment by TomnPhobos** [comment]
OK, yesterday i tested both cores a bit. And both of them work without crashing :) I hadn't mich time so i started the cores, loaded some programs (e.g. Prince2) and played a bit. I ran both cores for about 30 minutes each, The only thing i noticed was a hang with one core when i started the debugger on one of the disks. I have to check it out more, also which core it was. I also haven't tested the sound because i had no speackers attached to the MiST: I'll check out the cores more this wek (i have my MiST at home now) and give you some feedback.

**Comment by sorgelig** [comment]
Thanks! 
I've released new version with better timings, so you can try updated core.

**Comment by TomnPhobos** [comment]
Sorry for the late answer. Ah, great, i'll try this core out this weekend / next week :)

**Comment by TomnPhobos** [comment]
I checked out the cores a bit last weekend. I could only start the two test cores, not the one from the release folder. The monitor gives me an out-of-resolution error. Could it be that you start this core in the RGBS output mode as default? I don't have any ini-file on my SD-card.

**Comment by sorgelig** [comment]
this is weird.
Can you try new release?

**Comment by TomnPhobos** [comment]
OK, i'm back home on thursday and will it try out then

**Comment by sorgelig** [comment]
I've checked commits and now i remember i've tweaked the sync a little. 
Before there were 312 lines per frame, but real hardware had 320 lines. So, I've changed to 320 lines in my core as well for 100% match. May be it's crucial for your monitor since 50Hz is already too low. And with 320 lines it becomes 48.8Hz.

**Comment by TomnPhobos** [comment]
Ah, ok, that could be. I tested it with a Samsung LCD monitor. Next week i can check it with an Eizo monitor. Actually this monitor doesn't have problems with any of the other cores so i think it will also display the new core properly. I'll keep you informed :-)

**Comment by TomnPhobos** [comment]
OK, i just checked out the latest core with my small do-it-yourself 5,6" LCD monitor. and VGA input. And it works perfect :)
I checked out some things, all started without problems. Also the screen looks nice and crisp. So i think i can close the issue now ;)

![dsc_0470](https://cloud.githubusercontent.com/assets/17750695/14587585/98f473ee-04b5-11e6-8a2b-b86a97f59e4a.JPG)
